name: I18n Changes

on:
  push:
    paths:
      - "src/i18n/ua/**"

jobs:
  check-i18n-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print changed files
        run: |
          git diff --name-only ${{ github.sha }}~1..${{ github.sha }} -- src/i18n/ua/
