name: I18n Folder Monitor
on:
  push:
    paths:
      - 'src/i18n/ua/**'

jobs:
  monitor_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display changes
        run: |
          echo "Changes in i18n/ua folder:"
          git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '^src/i18n/ua/'