name: Convert JS to JSON

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert JS to JSON
        run: find ./src/i18n -type f -name "*.js" | xargs -I {} sh -c 'node -e "const data = require(\'{}\'); const fs = require(\'fs\'); fs.writeFileSync(\'{}.json\', JSON.stringify(data, null, 2));"'

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Convert JS to JSON"
          git push
