name: Translate locales js

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read target languages from file
        id: read-languages
        run: |
          echo "::set-output name=languages::$(cat locales-list.txt)"
      - name: Translate with Microsoft Translator
        id: translate
        run: |
          function containsElement() {
            local e
            for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
            return 1
          }

          langs=$(sed 's/$/&\&to=/g' locales-list.txt | tr -d '\n' | sed 's/\&to=$//')
          mkdir -p src/i18n
          files_to_compare=()

          for file in src/i18n/ua/*.js; do
            filename=$(basename "$file")
            all_subdirs_have_filename=true
            do_request_to_translate=false

            for subfile in src/i18n/ua/*.js; do
              for subdir in src/i18n/*/; do
                subfile_in_subdir="$subdir$filename"
                duplicate=false

                if ! containsElement "$subfile_in_subdir" "${files_to_compare[@]}"; then
                  files_to_compare+=("$subfile_in_subdir")
                fi

                if [[ "$subfile_in_subdir" != "$subfile" ]]; then
                  if [[ ! -e "$subfile_in_subdir" ]]; then
                    all_subdirs_have_filename=false
                    break
                  fi
                fi
              done
            done

            if [[ $all_subdirs_have_filename == true ]]; then
              if (( ${#files_to_compare[@]} > 1 )); then
                npm i esm
                result=$(node compare-locales.js "${files_to_compare[@]}")
                status=$(echo "$result" | jq -r '.status')
                if [[ $status == "SUCCESS" ]]; then
                  do_request_to_translate=true
                  echo $do_request_to_translate
                fi
              else
                do_request_to_translate=true
              fi
              files_to_compare=()
            else
              do_request_to_translate=true
              echo "$subfile: Not all subdirectories have $filename"
            fi

            if [[ $do_request_to_translate == true ]]; then
              file_content=$(cat "$file")
              echo $file_content
              translated_text=$(curl -s -X POST "https://blanball.cognitiveservices.azure.com/translator/text/v3.0/translate?api-version=3.0&from=uk&to=$langs" \
                -H "Content-Type: application/json" \
                -H "Ocp-Apim-Subscription-Key: a32cf006d7184a00bb73f23b5a9d154a" \
                -d "[
                  {
                    \"text\": \"export default { message: "Повідомлення", messages_not_avaliable: "Повідомлення недоступні", write_message: "Написати повідомлення...", you_were_kicked_from_the_chat_small: "Шкода, але вас було виключено із групи. Відправка повідомлень у цьому чаті більше недоступна.", you_were_kicked_from_the_chat: "Шкода, але вас було виключено із групи. Відправка повідомлень у цьому чаті більше недоступна. Ви можете звернутися до адміністрації каналу за додатковою інформацією", select_chat_from_the_list: "Оберіть чат, щоб розпочати спілкування", user_joined_to_chat: "{userFullName} щойно долучився до бесіди", members: "Учасники", online: "У мережі", message_edited: "ред.", message_editing: "Редагування повідомлення", emoji_groups: { smileys_people: "Посмішки та люди", animals_nature: "Тварини та природа", food_drink: "Їжа та напої", activities: "Діяльності", travel_places: "Місця для подорожей", objects: "Об`єкти", symbols: "Символи", flags: "Прапори", }, no_chat_messages: { title: "У цьому чаті ще не було повідомлень", main_text: "Надішліть повідомлення першим, щоб розпочати бесіду вже зараз!", }, edit_chat_modal: { select_photo: "Обрати фото", manage_group: "Керування групою", name_of_group_chat: "Назва бесіди", invitation_link: "Посилання-запрошення", }, submit_close_edit_chat_modal: { title: "Скасувати редагування групового чату", description: "Ви дійсно хочете скасувати всі внесені зміни?", button_1: "Ні, не скасосувати", button_2: "Так, скасувати", }, admins_limit_reached_modal: { title: "Перевищення ліміту", main_text: "Ви можете призначити не більше 3 модераторів.", }, toasts: { chat_link_copieded_success: "Посилання-запрошення на чат було успішно скопійовано в буфер обміну", chat_updated_success: "Дані цього групового чату було успішно змінено", }, roles: { admin: "Адмін", author: "Організатор", }, buttons: { set_admin: "Зробити адміном", unset_admin: "Забрати адміна", enable_push_notifications: "Увімкнути сповіщення", disable_push_notifications: "Вимкнути сповіщення", leave_group: "Покинути групу", delete_chat: "Видалити чат", search_messages: "Пошук повідомлень", manage_group: "Керування групою", }, };\"
                  }
                ]")
              target_lang=$(echo "$translated_text" | jq -r '.[0].translations[0].to')
              mkdir -p "src/i18n/$target_lang"
              echo "$translated_text" | jq -r '.[0].translations[0].text' > "src/i18n/$target_lang/$filename"
            fi
          done
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -am "Update translations"
      - name: Push changes
        if: steps.commit.outputs.returncode == 0
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ github.ref_name }}
          github_token: ${{ secrets.AUTH_TOKEN }}
