name: Translate locales js

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read target languages from file
        id: read-languages
        run: |
          echo "::set-output name=languages::$(cat locales-list.txt)"
      - name: Translate with Microsoft Translator
        id: translate
        run: |
          for lang in ${{ steps.read-languages.outputs.languages }}; do
            mkdir -p src/i18n/$lang
            for file in src/i18n/ua/*.js; do
              filename=$(basename "$file")
              file_content=$(cat "$file")
              translated_text=$(curl -s -X POST "https://api.cognitive.microsofttranslator.com/translator/text/v3.0/translate" \
              -H "Content-Type: application/json" \
              -H "Ocp-Apim-Subscription-Key: a32cf006d7184a00bb73f23b5a9d154a" \
              -d "[
                {
                  \"from\": \"ua\",
                  \"to\": \"$lang\"
                  \"text\": \"$file_content\",
                }
              ]")
              echo $translated_text
            done
          done
