name: Translate locales js

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Subfolders
        id: subfolders
        run: |
          SUBFOLDERS=$(find src/i18n -type d -print0 | xargs -0)
          echo "::set-output name=subfolders::$SUBFOLDERS"

      - name: DeepL Translate Github Action
        run: echo ${{ steps.subfolders.outputs.subfolders }}
