name: Translate locales js

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read target languages from file
        id: read-languages
        run: |
          echo "::set-output name=languages::$(cat locales-list.txt)"
      - name: Translate with Microsoft Translator
        id: translate
        run: |
          for lang in ${{ steps.read-languages.outputs.languages }}; do
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Ocp-Apim-Subscription-Key: a32cf006d7184a00bb73f23b5a9d154a" \
              -d '[
                {
                  "text": "Enter the text you want to translate here",
                  "to": "'"$lang"'"
                }
              ]' \
              "https://api.cognitive.microsofttranslator.com/"
          done