name: Translate locales js

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Subfolders
        id: subfolders
        run: |
          SUBFOLDERS=$(find src/i18n -type d -print0 | xargs -0 printf "%s\n")
          SUBFOLDERS=($SUBFOLDERS)
          echo "::set-output name=subfolders::${SUBFOLDERS[*]}"

      - name: DeepL Translate Github Action
        run: echo ${{ join(steps.subfolders.outputs.subfolders, ',') }}
